package ir.fararayaneh.erp.commons;


/**
 * set 1000 for fireBase notification channel and will be reserved
 */
public class CommonNotification {

    public static final String NOTIFICATIONS_CHANNEL_ID = "1001";
    public static final String FOREGROUND_NOTIFICATIONS_DOWNLOAD_APK_CHANNEL_ID = "1002";
    public static final String FOREGROUND_NOTIFICATIONS_UPLOAD_FILE_CHANNEL_ID = "1003";
    public static final String FOREGROUND_NOTIFICATIONS_EVACUATION_PACKET_CHANNEL_ID = "1004";
    public static final String FOREGROUND_NOTIFICATIONS_LOCATION_CHANNEL_ID = "1005";



    public static final String NOTIFICATIONS_CHANNEL_NAME = "ERP_CHANNEL_NAME";
    public static final String FOREGROUND_NOTIFICATIONS_DOWNLOAD_APK_CHANNEL_NAME = "FOREGROUND_ERP_DOWNLOAD_APK_CHANNEL_NAME";
    public static final String FOREGROUND_NOTIFICATIONS_UPLOAD_FILE_CHANNEL_NAME = "FOREGROUND_ERP_UPLOAD_FILE_CHANNEL_NAME";
    public static final String FOREGROUND_NOTIFICATIONS_EVACUATION_PACKET_CHANNEL_NAME = "FOREGROUND_ERP_EVACUATION_PACKET_CHANNEL_NAME";
    public static final String FOREGROUND_NOTIFICATIONS_LOCATION_CHANNEL_NAME = "FOREGROUND_NOTIFICATIONS_LOCATION_CHANNEL_NAME";

    public static final String NOTIFICATIONS_CHANNEL_DESCRIPTION = "ERP_CHANNEL_DESCRIPTION";
    public static final String FOREGROUND_NOTIFICATIONS_DOWNLOAD_APK_CHANNEL_DESCRIPTION = "FOREGROUND_ERP_DOWNLOAD_APK_CHANNEL_DESCRIPTION";
    public static final String FOREGROUND_NOTIFICATIONS_DOWNLOAD_UPLOAD_FILE_DESCRIPTION = "FOREGROUND_ERP_UPLOAD_FILE_CHANNEL_DESCRIPTION";
    public static final String FOREGROUND_NOTIFICATIONS_EVACUATION_PACKET_FILE_DESCRIPTION = "FOREGROUND_ERP_EVACUATION_PACKET_CHANNEL_DESCRIPTION";
    public static final String FOREGROUND_NOTIFICATIONS_LOCATION_DESCRIPTION = "FOREGROUND_NOTIFICATIONS_LOCATION_DESCRIPTION";


    public static final int NON_FOREGROUND_NOTIFICATIONS_ID = 1;
    public static final int FOREGROUND_DOWNLOAD_APK_NOTIFICATIONS_ID = 2;
    public static final int FOREGROUND_NOTIFICATIONS_UPLOAD_ID = 3;
    public static final int FOREGROUND_EVACUATION_PACKET_ID = 4;
    public static final int FOREGROUND_LOCATION_ID = 5;

    public static final String ACTION_STOP_SERVICE= "STOP_SERVICE";


}
